services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_BASE_URL=http://ollama-server:11434
      - OLLAMA_MODEL=qwen2.5:1.5b
    depends_on:
      - ollama-server
    volumes:
      - ./models:/app/models


  ollama-server:
    image: ollama/ollama:latest
    volumes:
      - ./ollama_models:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped


  train-rf:
    profiles: ["training"]
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m healthllm.train_rf
    environment:
      - MLFLOW_TRACKING_URI=sqlite:////mlflow/mlflow.db
      - MLFLOW_ARTIFACT_ROOT=/mlruns
    volumes:
      - ../data:/data
      - ./models:/app/models
      - ./reports:/app/reports
      - ./mlruns:/mlruns
      - ./mlflow:/mlflow

    
  mlflow:
    profiles: ["tracking"]
    image: ghcr.io/mlflow/mlflow:v3.7.0
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
      - ./mlflow:/mlflow
    command: mlflow ui --host 0.0.0.0 --backend-store-uri sqlite:////mlflow/mlflow.db --default-artifact-root /mlruns
