services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_BASE_URL=http://ollama-server:11434
      - OLLAMA_MODEL=qwen2.5:1.5b
    depends_on:
      - ollama-server

  ollama-server:
    image: ollama/ollama:latest
    volumes:
      - ./ollama_models:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped